[package]
name = "userutils"
version = "0.1.0"

[[bin]]
name = "getty"
path = "src/bin/getty.rs"

[[bin]]
name = "id"
path = "src/bin/id.rs"

[[bin]]
name = "login"
path = "src/bin/login.rs"

[[bin]]
name = "passwd"
path = "src/bin/passwd.rs"

[[bin]]
name = "su"
path = "src/bin/su.rs"

[[bin]]
name = "sudo"
path = "src/bin/sudo.rs"

[[bin]]
name = "whoami"
path = "src/bin/whoami.rs"

[dependencies]
argon2rs = { version = "0.2", default-features = false }
arg_parser = { git = "https://github.com/redox-os/arg-parser.git" }
extra = { git = "https://github.com/redox-os/libextra.git" }
liner = "0.1"
rand = "0.3"
redox_syscall = "0.1"
redox_termios = "0.1"
redox_users = { git = "https://github.com/goyox86/users.git" }
termion = "1.5.1"
